version: "3.7"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
      - .env.production
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
